@startuml
package Entities{
    abstract class Entity {
        # float x,y
        # int width,height
        # Rectangle2D.Float hitbox
        # int aniTick, aniIndex
        # int state
        # float airSpeed
        # boolean inAir = false
        # int maxHealth
        # int currentHealth
        # Rectangle2D.Float attackBox
        # float walkSpeed = 1.0f * Game.SCALE

            + Entity (float x, float y, int width, int height)
            + int getState()
            + Rectangle2D.Float getHitbox()
            + int getAniIndex()
            + int getCurrentHealth()
            # void drawAttack(Graphics g, int xlvOffset)
            # void drawHitbox(Graphics g, int xLvOffset)
            # void initHitbox(int width, int height)
    }

    class Player extends Entity {
        - BufferedImage[][] animations
        - boolean left,right,jump
        - boolean moving = false, attacking = false
        - int[][] levelData
        - float xDrawOffset = 21 * Game.SCALE
        - float yDrawOffset = 4 * Game.SCALE
        - float jumpSpeed = -2.25f * Game.SCALE
        - float fallSpeedAfterCollision = 0.5f * Game.SCALE
        - BufferedImage statusBarImg
        - int statusBarWidth
        - int statusBarHeight
        - int statusBarX
        - int statusBarY
        - int healthBarWidth
        - int healthBarHeight
        - int healthBarXStart
        - int healthBarYStart
        - int healthWidth
        - boolean attackChecked
        - Playing playing
        - int powerBarWidth
        - int powerBarHeight
        - int powerBarXStart
        - int powerBarYStart
        - int powerWidth = powerBarWidth
        - int powerMaxValue = 200
        - int powerValue = powerMaxValue
        - boolean powerAttackActive
        - int powerAttackTick
        - int powerGrowSpeed = 15
        - int powerGrowTick
        - int flipX = 0
        - int flipW = 1
        - int tileY = 0

            + Player(float x, float y, int width, int height, Playing playing)
            + void setSpawn(Point spawn)
            + void update()
            + void render(Graphics g, int lvOffset)
            + void changeHealth(int value)
            + void kill()
            + void changePower(int value)
            + void loadLevelData(int[][] levelData)
            + void resetDirBoolean()
            + void resetAll()
            + void setAttacking(boolean attacking)
            + boolean getLeft()
            + void setLeft(boolean left)
            + boolean getRight()
            + void setRight(boolean right)
            + void setJump(boolean jump)
            + int getTileY()
            + void powerAttack()
            - void initAttackBox()
            - void checkSpikeTrapTouched()
            - void checkPotionTouched()
            - void checkAttack()
            - void updateAttackBox()
            - void updateHealthBar()
            - void updatePowerBar()
            - void drawUI(Graphics g)
            - void updateAniTick()
            - void setAnimation()
            - void resetAniTick()
            - void updatePosition()
            - void jump()
            - void resetInAir()
            - void updateXPos(float xSpeed)
            - void loadAnimation()
            - void resetAttackBox()
    }
}
@enduml